### ISSUE TITLE
Consider opening CBM classes for subclassing

### ISSUE THREAD

**Issue by s-hocking** [NordicSemiconductor/IOS-CoreBluetooth-Mock#26]
The CBM library is great for simulating a full Bluetooth connection workflow, but sometimes I just want to satisfy a dependency on a CoreBluetooth object in order to test other parts of a class. For example, I might have a class with a dependency on a `CBPeripheral` object that I want to test without using any CoreBluetooth capabilities.

To achieve this use case it would be helpful if the core CBM classes were `open`, so that they could be subclassed and used this way.

Subclassing might also be a useful way of customising CBM behaviour for test purposes.

**Comment by philips77** [comment]
If you could prepare PR, I'll release the version.
