### ISSUE TITLE
The lowest supported version is iOS 9 but Package.swift has 8

### ISSUE THREAD

**Issue by NeverwinterMoon** [NordicSemiconductor/IOS-CoreBluetooth-Mock#37]
The title says it all

**Comment by philips77** [comment]
What errors do you get in 8?

**Comment by philips77** [comment]
OK, looks like I forgot to modify *Package.swift* file in here: https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/commit/a262272892632fabba7155542f7af5b3ab00aa2a.
