### ISSUE TITLE
Library does not compile with Xcode 13 beta/iOS 15 SDK due to CoreBluetooth API changes

### ISSUE THREAD

**Issue by zwift-aebling** [NordicSemiconductor/IOS-CoreBluetooth-Mock#41]
A number of inverse relationships in CoreBluetooth (e.g. `CBCharacteristic.service`) have been changed from `unowned(unsafe)` to `weak`, and therefore Optional in the iOS 15 SDK.

This results in numerous compilation errors when attempting use the IOS-CoreBluetooth-Mock library:

```
~/IOS-CoreBluetooth-Mock/CoreBluetoothMock/Classes/CBMCentralManagerNative.swift:391:51: Value of optional type 'CBService?' must be unwrapped to a value of type 'CBService'
```

**Comment by philips77** [comment]
I love Apple and it's approach to backwards compatibility. Thank you for letting us know! Could you, please, prepare a PR with a fix?

**Comment by zwift-aebling** [comment]
Will do!

**Comment by ricobeck** [comment]
Did it:
https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/pull/44

**Comment by philips77** [comment]
This should now work on *develop* branch after #50, #51 and #52.
