### ISSUE TITLE
CBCentralManager.authorization is not supported

### ISSUE THREAD

**Issue by NeverwinterMoon** [NordicSemiconductor/IOS-CoreBluetooth-Mock#46]
This is something that exists since iOS 13 (so, pretty old by now) and can be used to check app's authorization even before initing CBManager.

Sadly, using the recommended approach of aliasing for CBM, I had to hide my production code behind build configuration flags in order to be able to use CBM, as I am using `CBCentralManager.authorization`

So, would be nice to have `CBCentralManager.authorization` and `CBManagerAuthorization`

iOS 13.0: https://developer.apple.com/documentation/corebluetooth/cbmanager/3180033-authorization
iOS 13.1+: https://developer.apple.com/documentation/corebluetooth/cbmanager/3377595-authorization

**Comment by philips77** [comment]
Hi, could you please review #54?

**Comment by philips77** [comment]
The PR has been merged to *develop*.
