### ISSUE TITLE
CBCentralManagerMock#connect API differs from the real one

### ISSUE THREAD

**Issue by NeverwinterMoon** [NordicSemiconductor/IOS-CoreBluetooth-Mock#47]
This is minor, but still forced me to change the production code in order to accommodate for CBM.

With the real API there is a default nil value for options, so I used this: `centralManager.connect(retrievedPeripheral)`, with CBM, it's necessary to set options explicitly, even if it's a nil.

`open func connect(_ peripheral: CBPeripheral, options: [String : Any]? = nil)`
vs 
`open func connect(_ peripheral: CBMPeripheral, options: [String : Any]?)`

**Comment by philips77** [comment]
Fixed and will be released in the next version. I also fixed the same issue in `scanForPeripherals` and `registerForConnectionEvents` methods.
