### ISSUE TITLE
Would be nice if writeValue for characteristic with .notify triggered simulateValueUpdate automatically

### ISSUE THREAD

**Issue by NeverwinterMoon** [NordicSemiconductor/IOS-CoreBluetooth-Mock#48]
I might not be seeing some bigger picture, as I've only worked with one BLE device, but in my mind it makes sense to automatically trigger `simulateValueUpdate` whenever writing to a characteristic that has a .notify property. 

Once again, it's possible that I just don't see all the possible scenarios, but on the device I work with, every characteristic that is writable and can notify, notifies of the written change.

**Comment by philips77** [comment]
No, it's just in your implementation like this. Usually, if a characteristic has WRITE or WRITE_NO_RESPONSE properties and NOTIFY or INDICATE, the data you write trigger some action, confirmed later by notification and indication. The data you send and receive can be different. If you want the behavior you described, you need to implement it yourself in 
https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/blob/360ba1f26a99e5f90a0197bfa173b19c5c948ea2/CoreBluetoothMock/Classes/CBMPeripheralSpecDelegate.swift#L139-L142
or
https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/blob/360ba1f26a99e5f90a0197bfa173b19c5c948ea2/CoreBluetoothMock/Classes/CBMPeripheralSpecDelegate.swift#L150-L152
