### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by joeynelson42** [NordicSemiconductor/IOS-CoreBluetooth-Mock#7]
Hello,

Are there plans to support Carthage?

**Comment by philips77** [comment]
Sure this can be added.

**Comment by philips77** [comment]
Resolved in version 0.9.0: https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/releases/tag/0.9.0

**Comment by philips77** [comment]
Could you give it a spin?

**Comment by joeynelson42** [comment]
It's working great, thanks!

**Comment by philips77** [comment]
So I released 0.10.0 today. No functional changes unless you are using tvOS, watchOS or macOS. Just FYI. Also, the library should now be build for distribution (#8).
