### ISSUE TITLE
Task: Add support for SPM

### ISSUE THREAD

**Issue by kscheff** [NordicSemiconductor/IOS-CoreBluetooth-Mock#72]
Trying to get Xcode 13.4.1 compiling with the swift package alone doesn't work on my M1 machine (I did not check others). All options are based on Pods, so it is a long configuration fight in the project settings in order to get it proper compiling using the swift package. 

I have not check the Pod install, since it was a rough start with the M1.

Suggestion: move project to swift package instead of Pod install.

**Comment by philips77** [comment]
OK, will do that soon!

**Comment by NickKibish** [comment]
The project supports SPM.
