### ISSUE TITLE
Simulated peripheral name always nil

### ISSUE THREAD

**Issue by lumo2707** [NordicSemiconductor/IOS-CoreBluetooth-Mock#78]
When I am trying to simulate peripherals the name of the retrieved device is always nil.

What I did so far:

1. Create a mock peripheral

```swift
 let mockGateway1 = CBMPeripheralSpec
                .simulatePeripheral(proximity: .near)
                .advertising(
                    advertisementData: [
                        CBMAdvertisementDataLocalNameKey    : "mock1",
                        CBMAdvertisementDataServiceUUIDsKey : [CBMUUID(string: "f9505467-a5c5-42c2-95c8-0ec77aeXXXX")],
                        CBMAdvertisementDataIsConnectable   : true as NSNumber
                    ],
                    withInterval: 0.250,
                    alsoWhenConnected: false)
                .connectable(
                    name: "mock1",
                    services: [],
                    delegate: nil,
                    connectionInterval: 0.150,
                    mtu: 23)
                .build()
```

2. Call `simulatePeripherals` and `simulateInitalState:

```swift
         CBMCentralManagerMock.simulatePeripherals([mockGateway1])
            CBMCentralManagerMock.simulateInitialState(.poweredOn)
```

3. Then in `didDiscover` delegate I got one peripheral, but its name is always nil:

![image](https://user-images.githubusercontent.com/8993387/213860623-09c74c8e-e061-43e8-9dd1-445835efea16.png)

What did I wrong?

**Comment by philips77** [comment]
Hmm.. i need to check that. 
Your still can get the name from advertising data map with `CBMAdvertisementDataLocalNameKey` key, that should work.

**Comment by philips77** [comment]
OK, I managed to replicate the issue. Sorry for the long delay.

**Comment by lumo2707** [comment]
No problem, in the meantime I use the `CBMAdvertisementDataLocalNameKey` as workaround.
