### ISSUE TITLE
Unable to re-initialize native central manager after mock central manager initialized

### ISSUE THREAD

**Issue by kylewludwig** [NordicSemiconductor/IOS-CoreBluetooth-Mock#9]
When creating a "demo mode" for an application, it'd be great to be able to allow users to toggle between a "native" and "mock" central manager with all supported features of the device and software. This way users can evaluate how a product behaves before the purchase by just downloading the app.

I'd found that I can do it with this library with
`self.centralManager = CBMCentralManagerFactory.instance(delegate: CBMCentralManagerDelegate, queue: DispatchQueue?, options: [String: Any]?, forceMock: Bool)` by re-initializing a central manager with the `forceMock` toggled.

However, I've found this only works when the `CBMCentralManagerOptionRestoreIdentifierKey` is modified each time or omitted from `options:` in the `init` method above. Otherwise, the native centralManagerState `didUpdateState(_:)` returns `unsupported` after initialization if a native central manager was initialized beforehand (e.g. native > mock > native.) I've found the native central manager was able to call `deinit` but the mock central manager is unable to call `deinit` when this occurs.

For now, workarounds include:
1. using `CBMCentralManagerOptionRestoreIdentifierKey` only when `forceMock` = false,
2. remove this key and lose support for CoreBluetooth peripheral restoration, or
3. include a custom string for the key each time to enable it for the native centralManager again.

I'm using a similar `centralManager` and `peripheral` implementation to the Blinky example provided (using notification central and a reference cycle between the central manager and peripherals). I've also tried with and without setting the `CBMCentralManagerFactory.simulateStateRestoration` callback in the App Delegate:
```swift
CBMCentralManagerFactory.simulateStateRestoration = { identifier in
   return [
      CBMCentralManagerRestoredStatePeripheralsKey: [Seeds.Peripherals.downrigger.identifier],
      CBMCentralManagerRestoredStateScanServicesKey: [],
      CBMCentralManagerRestoredStateScanOptionsKey: [
         CBMCentralManagerScanOptionAllowDuplicatesKey: false,
         CBMCentralManagerScanOptionSolicitedServiceUUIDsKey: []
      ]
   ]
}
```

This issue should be easily replicated by adding a print statement in the centralManager `deinit` method and toggling between a native and mock central manager; observing the method is only called when the central manager is native.

**Comment by philips77** [comment]
Thank you for the feedback. I'll look into it when I have some time.

**Comment by kylewludwig** [comment]
Thanks in advance! See the last comment in this thread from RxBluetoothKit; it looks like a similar issue. If this is the case, it could very well be my code causing this memory leak, too. I just haven't found it yet.

https://github.com/Polidea/RxBluetoothKit/issues/264

**Comment by kylewludwig** [comment]
I found the issue at this line caused the memory leak; keeping the previous `CBMCentralManagerNative` from calling `deinit`:
https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/blob/835c9785d41b824218f86c78154a61a3b3abb297/CoreBluetoothMock/Classes/CBMCentralManagerNative.swift#L41

My fix was to change the line to use a weak reference to the manager with force unwrapping to minimize changes:
`fileprivate weak var manager: CBMCentralManagerNative!`

If you'd like to make the change, feel free. I can also make a fork and formal PR though if you'd like 🙂

**Comment by philips77** [comment]
Fixed.
